name: CI/CD

on:
  push:
    branches-ignore:
      - main
  pull_request:

env:
  DOTNET_DOWNLOAD_URL: "https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.100/dotnet-sdk-8.0.100-linux-x64.tar.gz"
  DOTNET_SDK_VERSION: "8.0.100"
  DOTNET_FILE: "dotnet-sdk-8.0.100-linux-x64.tar.gz"
  ARTIFACT_NAME: "le_baguette"
  SECRETS_MANAGER_ACCESS_TOKEN: ${{ secrets.SECRETS_MANAGER_ACCESS_TOKEN }}
  ASPNETCORE_ENVIRONMENT: "Development"
  PATCH_VERSION: ${{ github.run_number }}

jobs:
  ci:
    runs-on: ubuntu-latest
    
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.TOKEN }}
      - name: Download & install .NET SDK
        run: |
          mkdir dotnet
          cd dotnet
          curl -LO ${{ env.DOTNET_DOWNLOAD_URL }}
          tar zxf ${{ env.DOTNET_FILE }}
          rm -R ${{ env.DOTNET_FILE }}
          cd ../
          sudo rm -R /usr/share/dotnet
          sudo mv -f ./dotnet /usr/share/
      - name: Replace placeholder version
        run: |
          sed -i 's/5123.0.0/${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ env.PATCH_VERSION }}/' ./Config/Config.csproj
      - name: Run tests
        run: |
          mkdir bin
          cd bin
          curl -LO https://github.com/bitwarden/sdk/releases/download/bws-v0.3.0/bws-x86_64-unknown-linux-gnu-0.3.0.zip
          unzip bws-x86_64-unknown-linux-gnu-0.3.0.zip
          chmod +x bws
          export PATH=$PATH:$PWD
          cd ../
          dotnet test CuplanConfig.sln